version: "3"

services:
  database:
    image: "postgres:12-alpine"

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails7_api_development

    volumes:
      - ./tmp/db-data/:/var/lib/postgresql/data/
